#cloud-config

package_update: true

packages:
 - python3-pip
 - groff
 - ruby-full

runcmd:
  - [ sh, -c, "pip3 install --upgrade awscli && pip3 --version && aws --version" ]
  - [ sh, -c, "aws s3 ls > /home/ubuntu/s3-acess-verification.txt" ]
  - [ sh, -c, "chown ubuntu:ubuntu /home/ubuntu/s3-acess-verification.txt" ]
  - [ sh, -c, "gem install safedb" ]
  - [ sh, -c, "git clone ${git_credentials_url} /home/ubuntu/credentials" ]
  - [ sh, -c, "chown -R ubuntu:ubuntu /home/ubuntu/credentials" ]
