#cloud-config

package_update: true

packages:
 - python3-pip
 - groff

runcmd:
  - [ sh, -c, "sudo pip3 install --upgrade awscli && pip3 --version && aws --version" ]
  - [ sh, -c, "aws s3 ls > /home/ubuntu/s3-acess-verification.txt" ]
