#cloud-config

package_update: true

packages:
 - python3-pip
 - groff
 - ruby-full

runcmd:
  - [ sh, -c, "pip3 install --upgrade awscli && pip3 --version && aws --version" ]
  - [ sh, -c, "gem install safedb" ]
  - [ sh, -c, "git clone ${git_credentials_url} /home/ubuntu/credentials" ]
  - [ sh, -c, "chown -R ubuntu:ubuntu /home/ubuntu/credentials" ]
  - [ sh, -c, "echo \"alias safetty='export SAFE_TTY_TOKEN=\\`safe token\\`'\" >> /home/ubuntu/.bash_aliases" ]
  - [ sh, -c, "chown ubuntu:ubuntu /home/ubuntu/.bash_aliases" ]
  - [ sh, -c, "curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.6.13/bin/linux/amd64/kubectl --output /usr/local/bin/" ]
  - [ sh, -c, "chmod +x /usr/local/bin/kubectl" ]
